

""""
Complementing a Strand of DNA
url: http://rosalind.info/problems/revc/

Given: A DNA string  of length at most 1000 bp.
Return: The reverse complement sc of s. .
"""

def DNAstrand(string):
    strand = ""
    for i in string[::-1]:
        if i == "A":
            strand += "T"
        if i == "T":
            strand += "A"
        if i == "C":
            strand += "G"
        if i == "G":
            strand += "C"
    return strand


if __name__ == "__main__":
    with open("/media/ekramah/DISK2/Rosaland_Problams_Solution/rosalind_daily_challenge/rosalind_problems/rosalind_revc.txt", "r") as f:
        string = f.readline().strip()
        strand = DNAstrand(string)
        print(strand)




"""OR Another SIMPLER WAY:

st = "TCGGGTTCAAAACAATGGACTCCCGTTCAGCCATTGGGTCGAGTTCTCTGCTGCCCTGACGAACGTAGTGTGGTCACCCGCGATCAGCGCAATCTACGAGACGAGCCTCGAGATCGAGACACTGCACACTCCGGTCGCTTACGGGCATGCCCAGGTCACACCGGGAGGCCAAACTCGTGTCGGCCTTACCTAATGGCTCCCGGGCGGCTGCTGGTCGCTTTCACGCAAAGCTAAACTTTGCTTTAGACTCGGCTTTCGTATAAGATCCACTTGCGGAACCGAGTACTTAACACTACGAGTATTTGCCACGACGCGATTCTTGCTCCGGCATACGATTCCAACATTATCAATAGACAGGACGCACCAGACTCAGTCCTAAACTATGTTGGTCACACGTTATGATTGCGGCTGTAGAACGGTTTATGGGGCCAGCTGGTGAATAGAGGGGCCTTTTCGTCTGCACCCACTATGTGGTGGCAGTCTCAATTTTGCTGACATAGGCAGGCTAAGCAGGTCCTCTGCAACTCCCAAGCACGAGGTGTCGGATGCGAGAGTCAAGCGATGGCAGGTTCGGGCATGCGCTGCTTGCATGTATTTGCGTATATGGGCTTACCACGACAGCTACTCGAACGCGTCACCAAGCACCGACTCCGTCTCGAAATTCAGTCGTTTATGACTGTGTGGGATTTATAACCTCAGAATTCTCTTGATGGTTGCTTAGTATTCGATCATGTCCACCTTTAAGGCTTGTAGTTGGTGTACGACAGCCAAACCGCGCACGTAGTCTATATGTTTGTAAGGGACGAGGAAGGGTTTTAATATGCAAAAGACCTTATTCTCCTCAGTGGAGCGATCAATCAAAAGGGCTCAGGATGGGTATAAGGGGACGAAGAGGTACATTGCTACTTGCCGTATTCTCTGAAAAGCAAGAAGCTATAGGGGACACTCAGTGCGGATCGCCCGGTCTTTATAGGCACATTTTTG"
st = st.replace('A', 'T').replace('T', 'A').replace('C', 'G').replace('G', 'C').upper()[::-1]
print (st)
"""